name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Publish Plugin to MavenLocal
        run: ./gradlew :wspb-gradle-plugin:publishToMavenLocal --configure-on-demand --no-daemon

      - name: Check spotless
        run: ./gradlew spotlessCheck --no-configuration-cache

      - name: Check lint
        run: ./gradlew lint

      - name: Upload lint reports (HTML)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: '**/build/reports/lint-results-*.html'

      - name: Build app
        run: ./gradlew :sample-app:assemble -PminifyWithR8=false --no-daemon
