package com.wonseok.wspb.gradle.plugin

import com.android.build.api.variant.AndroidComponentsExtension
import com.android.build.gradle.BaseExtension
import com.google.protobuf.gradle.ProtobufExtension
import com.google.protobuf.gradle.proto
import com.wonseok.convention.libs
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.dependencies

/**
 * Gradle plugin that connects the KSP-generated `.proto` files to the protobuf
 * Gradle plugin for Android projects.
 *
 * After this plugin is applied:
 * 1. the protobuf plugin is applied automatically,
 * 2. `protoc` is configured to generate Java lite classes,
 * 3. each Android variant sees the `.proto` resources generated by KSP, and
 * 4. the protobuf lite runtime is added to the project's dependencies.
 */
class WSPBConventionPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        with(project) {
            with(plugins) {
                // The protobuf plugin performs the actual `.proto` -> Java
                // generation step. This convention plugin wires everything
                // around it so app and library modules do not need repeated
                // setup in their own build scripts.
                apply(libs.findPlugin("protobuf").get().get().pluginId)

                withId(libs.findPlugin("android-application").get().get().pluginId) {
                    configureProtoSourceSets()
                }

                withId(libs.findPlugin("android-library").get().get().pluginId) {
                    configureProtoSourceSets()
                }
            }

            configure<ProtobufExtension> {
                protoc {
                    // Pin the `protoc` binary through the version catalog so the
                    // generated classes are reproducible across projects.
                    artifact = libs.findLibrary("protobuf-protoc").get().get().toString()
                }

                generateProtoTasks {
                    all().forEach { task ->
                        task.builtins {
                            register("java") {
                                // Android projects usually want the lite runtime
                                // because it keeps generated code and runtime
                                // dependencies smaller.
                                option("lite")
                            }
                        }
                    }
                }
            }

            dependencies {
                // Generated Java lite sources depend on the protobuf lite runtime
                // at compile time and runtime.
                add("implementation", libs.findLibrary("protobuf-kotlin-lite").get())
            }
        }
    }

    /**
     * Adds the KSP-generated resource directory to each Android variant's proto
     * source set so the protobuf plugin can pick up the generated schemas.
     */
    private fun Project.configureProtoSourceSets() {
        extensions.configure<AndroidComponentsExtension<*, *, *>>("androidComponents") {
            onVariants { variant ->
                // KSP writes generated resources under the build directory using
                // the current variant name, for example `debug` or `release`.
                val protoDir =
                    layout.buildDirectory.dir("generated/ksp/${variant.name}/resources")

                extensions.configure<BaseExtension>("android") {
                    sourceSets.getByName(variant.name) {
                        proto {
                            srcDir(protoDir)
                        }
                    }
                }
            }
        }
    }
}
